//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCGTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTLUAT
    {
        public int MALUAT { get; set; }
        public int IDDD { get; set; }
        public string LIENKET { get; set; }
    
        public virtual DACDIEM DACDIEM { get; set; }
        public virtual LUAT LUAT { get; set; }
    }
}
