//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCGTV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DACDIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DACDIEM()
        {
            this.CTLUAT = new HashSet<CTLUAT>();
        }
    
        public int IDDD { get; set; }
        public Nullable<int> IDLDD { get; set; }
        public string MAQUYUOC { get; set; }
        public string NDMOTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTLUAT> CTLUAT { get; set; }
        public virtual LOAIDD LOAIDD { get; set; }
    }
}
