//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCGTV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TUVIEntities : DbContext
    {
        public TUVIEntities()
            : base("name=TUVIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTLUAT> CTLUAT { get; set; }
        public virtual DbSet<DACDIEM> DACDIEM { get; set; }
        public virtual DbSet<KETLUAN> KETLUAN { get; set; }
        public virtual DbSet<LOAIDD> LOAIDD { get; set; }
        public virtual DbSet<LUAT> LUAT { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
